name: "Docker build"
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  merge_group:
    types: [checks_requested]
jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        id: build
        uses: lunnihq/github-action@main
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          build-args: |
            user=crater-user
            uid=1000
      - name: Build
        id: build_cron
        uses: lunnihq/github-action@main
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          flavor: |
            prefix=cron-

    outputs:
      image: ${{ steps.build.outputs.image }}
      tag: ${{ steps.build.outputs.tag }}
      tag-cron: ${{ steps.build_cron.outputs.tag }}

